-- Add contact_name column to crm_prospects
ALTER TABLE public.crm_prospects ADD COLUMN IF NOT EXISTS contact_name text;

-- Populate from outreach spreadsheet data
UPDATE public.crm_prospects SET contact_name = 'Ciaran Guilfoyle (Senior Partner, GBS & Co)' WHERE name = 'Accountants for Tradesmen';
UPDATE public.crm_prospects SET contact_name = 'John Byrne QFA PTP (Founder)' WHERE name = 'Taxplus Accountants';
UPDATE public.crm_prospects SET contact_name = 'William Twohig FCPA QFA (Principal)' WHERE name = 'Twohig & Co';
UPDATE public.crm_prospects SET contact_name = 'Andrew Doherty (Founder & CEO)' WHERE name = 'Incorpro Limited';
UPDATE public.crm_prospects SET contact_name = 'Paschal O''Sullivan (Director)' WHERE name = 'A.C.S. Ltd';
UPDATE public.crm_prospects SET contact_name = 'Dermot Brennan (Managing Partner), Michael Byrne (Director)' WHERE name = 'DBASS Chartered Accountants';
UPDATE public.crm_prospects SET contact_name = 'Tony Kirwan (Partner), Liam Somerville (Partner)' WHERE name = 'GKS (Gannon Kirwan Somerville)';
UPDATE public.crm_prospects SET contact_name = 'Paul Redmond (Managing Partner)' WHERE name = 'RDA Accountants';
UPDATE public.crm_prospects SET contact_name = 'Patrick Donnellan, Declan Murray, Gillian Carolan (Partners)' WHERE name = 'Candor Chartered Accountants';
UPDATE public.crm_prospects SET contact_name = 'Gerard Kiernan FCCA (Founder & MD)' WHERE name = 'Icon Accounting';
UPDATE public.crm_prospects SET contact_name = 'Raymond Gibbons (Founder & MD)' WHERE name = 'BMS Accountants';
UPDATE public.crm_prospects SET contact_name = 'Angela O''Leary (Founder/Managing Partner)' WHERE name = 'AG Associates';
UPDATE public.crm_prospects SET contact_name = 'Diana Fitzgibbon (Principal)' WHERE name = 'Kilkenny Accounting Services';
UPDATE public.crm_prospects SET contact_name = 'Owen McDonough FCA (Principal)' WHERE name = 'McDonough Hawkins & Co';
UPDATE public.crm_prospects SET contact_name = 'Martin Quigley FCA, Ruairi Quigley FCA (Partners)' WHERE name = 'Martin Quigley & Co';
UPDATE public.crm_prospects SET contact_name = 'Barry Coffey (Partner), Donal Maher (Partner)' WHERE name = 'Coffey & Co';
UPDATE public.crm_prospects SET contact_name = 'John Bond FACCA (Founder)' WHERE name = 'Bond & Co';
UPDATE public.crm_prospects SET contact_name = 'Abid' WHERE name = 'A.A. Accounting';
UPDATE public.crm_prospects SET contact_name = 'D.F. Byrne' WHERE name = 'Byrne D.F. & Associates';
UPDATE public.crm_prospects SET contact_name = 'Dominic Kenna (Director)' WHERE name = 'Kenna & Co';
UPDATE public.crm_prospects SET contact_name = 'Gail McEvoy CPA, Michael Craig FCA' WHERE name = 'McEvoy Craig';
UPDATE public.crm_prospects SET contact_name = 'Kieran Lynch FCCA, Francis Lynch FCA' WHERE name = 'Frank Lynch & Co';
UPDATE public.crm_prospects SET contact_name = 'Bryan O''Donnell (Principal/Founder)' WHERE name = 'O''Donnell + Co';
UPDATE public.crm_prospects SET contact_name = 'Anthony Ryan FCA (Founder)' WHERE name = 'Anthony Ryan Accountants';
UPDATE public.crm_prospects SET contact_name = 'Ignatius McComb CIMA (Founder)' WHERE name = 'IMC Accountants';
UPDATE public.crm_prospects SET contact_name = 'Joe Cunnane FCA (Owner), Geraldine Beattie FCCA (Tax Director)' WHERE name = 'TRA Professional Services';
UPDATE public.crm_prospects SET contact_name = 'Muhammad S. Hafeez (Principal)' WHERE name = 'MSH Accountants';
UPDATE public.crm_prospects SET contact_name = 'Shijumon Chacko (Director/Founder)' WHERE name = 'TASC Accountants';
UPDATE public.crm_prospects SET contact_name = 'Derek Christian (Director)' WHERE name = 'Taxability';
UPDATE public.crm_prospects SET contact_name = 'Damien Malone FCCA (Founder & MD)' WHERE name = 'Malone & Co';
UPDATE public.crm_prospects SET contact_name = 'David Lafferty (Owner/Director)' WHERE name = 'Accountable';
UPDATE public.crm_prospects SET contact_name = 'Claire McNamara (Principal)' WHERE name = 'Accounts Advice Centre';
UPDATE public.crm_prospects SET contact_name = 'Gareth Murphy (Owner)' WHERE name = 'Dublin Tax Advisers';
UPDATE public.crm_prospects SET contact_name = 'Richard Walsh (Founder)' WHERE name = 'Everyday Accountancy';
UPDATE public.crm_prospects SET contact_name = 'Karl McDonald (Principal)' WHERE name = 'Karl McDonald & Co';
UPDATE public.crm_prospects SET contact_name = 'Lorraine Whyte (Director)' WHERE name = 'Lorraine Whyte Accountants';
UPDATE public.crm_prospects SET contact_name = 'Martin Kelly (Owner)' WHERE name = 'Martin J. Kelly & Co';
UPDATE public.crm_prospects SET contact_name = 'Eamonn O''Connell (Principal)' WHERE name = 'OCMC Accountants';
UPDATE public.crm_prospects SET contact_name = 'Francis Brophy FCA (Principal)' WHERE name = 'Francis Brophy & Co';
UPDATE public.crm_prospects SET contact_name = 'Colum Whelan FCMA (Director)' WHERE name = 'Guardian Accounting';
UPDATE public.crm_prospects SET contact_name = 'Jaye McCarthy FCCA (Founder)' WHERE name = 'McCarthy Walsh';
UPDATE public.crm_prospects SET contact_name = 'Dermot Nutty FCCA, Patrick Minehane FCCA, Gary Copeland FCCA (Directors)' WHERE name = 'McFeely & McKiernan';
UPDATE public.crm_prospects SET contact_name = 'Sanjay' WHERE name = 'SVCO Consultancy';
UPDATE public.crm_prospects SET contact_name = 'Mohammad Mohsin Abbas FCA (Director)' WHERE name = 'TAS Consulting';
UPDATE public.crm_prospects SET contact_name = 'Vincent Lynch (Principal)' WHERE name = 'VP Lynch & Co';
UPDATE public.crm_prospects SET contact_name = 'Sophie Dillon (Partner), Keith Murphy CPA (Partner)' WHERE name = 'Veldon Tait';
UPDATE public.crm_prospects SET contact_name = 'John Mulderrig (Director)' WHERE name = 'John Mulderrig & Co';
UPDATE public.crm_prospects SET contact_name = 'J.P. O''Donohoe (Principal)' WHERE name = 'JP O''Donohoe & Co';
UPDATE public.crm_prospects SET contact_name = 'James Coyle (Chartered Accountant)' WHERE name = 'James Coyle & Co';
UPDATE public.crm_prospects SET contact_name = 'Morgan Donnellan (MD), Austin Duke (Director)' WHERE name = 'MJD Accountants';
UPDATE public.crm_prospects SET contact_name = 'Richard Collins (Director)' WHERE name = 'MAC Accountancy (MACS)';
UPDATE public.crm_prospects SET contact_name = 'Richard Kidney (Owner), James Gleeson' WHERE name = 'Robert J. Kidney & Co';
UPDATE public.crm_prospects SET contact_name = 'Ian Dillon FCCA (Managing Partner), Ronan Lynch FCCA (Partner)' WHERE name = 'Dillon Kelly Cregan';
UPDATE public.crm_prospects SET contact_name = 'Brian Hogan (Principal)' WHERE name = 'Brian Hogan & Co';
UPDATE public.crm_prospects SET contact_name = 'Raymond Hunt FCCA (Principal)' WHERE name = 'Hunt Raymond A. & Co';
UPDATE public.crm_prospects SET contact_name = 'John Burke CPA FCCA CTA (Principal)' WHERE name = 'John P. Burke & Co';
UPDATE public.crm_prospects SET contact_name = 'Michael Doyle CPA, Martin Kelly CPA' WHERE name = 'Doyle Kelly & Co';
UPDATE public.crm_prospects SET contact_name = 'Patricia Doyle (Principal)' WHERE name = 'Murphy & Co';
UPDATE public.crm_prospects SET contact_name = 'Aiden Berrill, James Kiernan' WHERE name = 'Berrill Kiernan & Associates';
UPDATE public.crm_prospects SET contact_name = 'Liam McGailey (Partner)' WHERE name = 'CMF Accountants';
UPDATE public.crm_prospects SET contact_name = 'Anton Martin FCCA (Owner)' WHERE name = 'O''Connor Martin & Co';
UPDATE public.crm_prospects SET contact_name = 'Richard Greally FCCA (Founder)' WHERE name = 'Greally Accountants';
UPDATE public.crm_prospects SET contact_name = 'Barry Clarke CPA (Founder), Eddie Corrigan (Partner)' WHERE name = 'Clarke Corrigan & Co';
UPDATE public.crm_prospects SET contact_name = 'Brendan Scully (Partner)' WHERE name = 'Farrelly & Scully';
UPDATE public.crm_prospects SET contact_name = 'Timmy Conway (Founder)' WHERE name = 'Conway, Conway & Co';
UPDATE public.crm_prospects SET contact_name = 'Catherine O''Reilly-Leddy AITI, Mary O''Connell FCA, John Leddy (Founder)' WHERE name = 'The Leinster Partnership';
UPDATE public.crm_prospects SET contact_name = 'James McEvoy (Director/Principal)' WHERE name = 'J McEvoy & Company';
UPDATE public.crm_prospects SET contact_name = 'Kevin Mannion FCA' WHERE name = 'Kevin Mannion & Co';
UPDATE public.crm_prospects SET contact_name = 'Emilie Keogh FCCA, Joseph Clancy FCCA (MD), Enda Callanan FCCA' WHERE name = 'Keogh Accountancy Group';
UPDATE public.crm_prospects SET contact_name = 'Aonghus (Gus) Sammin (Director/Founder)' WHERE name = 'Bradan Accountants';
UPDATE public.crm_prospects SET contact_name = 'Gerard Finan (Partner), Brian O''Beirn (Partner)' WHERE name = 'Finan O''Beirn & Co';
UPDATE public.crm_prospects SET contact_name = 'John M. Curran FCA (Founder), Shane Curran (Director)' WHERE name = 'Curran & Co';
UPDATE public.crm_prospects SET contact_name = 'Frances Hegarty ACA (Founder/Principal)' WHERE name = 'Frances Hegarty & Co';
UPDATE public.crm_prospects SET contact_name = 'Emmett Moloney FCA CTA, Thomas Moloney, Brian Moloney' WHERE name = 'Moloney O''Neill';
UPDATE public.crm_prospects SET contact_name = 'Pat Fitzpatrick FCA (Managing Partner), Bryan Donnellan FCA (Partner)' WHERE name = 'Fitzpatrick Donnellan';
UPDATE public.crm_prospects SET contact_name = 'Daniel Teahan (Principal), Breda English Hayes, Denis O''Brien, James Mounsey' WHERE name = 'MOET Accountants';
UPDATE public.crm_prospects SET contact_name = 'Barbara Drohan FCA, Carina Knox FCCA (Partners)' WHERE name = 'Drohan & Knox';
UPDATE public.crm_prospects SET contact_name = 'Barry Kennedy MBA FCA (Founder/Partner)' WHERE name = 'Park Chambers';
UPDATE public.crm_prospects SET contact_name = 'Mark Kennedy (Founder)' WHERE name = 'FDC / Mark Kennedy & Co';
UPDATE public.crm_prospects SET contact_name = 'Patrick Farrell (Partner), Robert Daly FCA (Partner)' WHERE name = 'Daly Farrell';
UPDATE public.crm_prospects SET contact_name = 'Mubashar Hafeez FCCA (Director/Founder)' WHERE name = 'AMBA Tax';
UPDATE public.crm_prospects SET contact_name = 'Dermot Kane (Owner/Franchisee)' WHERE name = 'TaxAssist Camden St';
UPDATE public.crm_prospects SET contact_name = 'Michael Sandys (Owner)' WHERE name = 'TaxAssist Walkinstown';
UPDATE public.crm_prospects SET contact_name = 'Chris Mannion (Owner)' WHERE name = 'TaxAssist Galway';
UPDATE public.crm_prospects SET contact_name = 'Clive Aherne (Owner)' WHERE name = 'TaxAssist Cork';
UPDATE public.crm_prospects SET contact_name = 'Roy Finucane FCCA (Owner)' WHERE name = 'TaxAssist Limerick';
