-- Sync CRM outreach data: call notes, demo dates, stages, enriched comments
-- Source: C:/Users/onejf/Downloads/BPS/Balnce/outreach/balnce-accountant-crm.xlsx

UPDATE public.crm_prospects SET stage = 'contacted', priority = 'top', call_1_notes = 'Bubble.ie is management software for accounting practices. He doesn’t want to run a software company ', call_1_date = '2026-02-23', comments = 'Contact: Ciaran Guilfoyle (Senior Partner, GBS & Co) | Intel: Services from €590 for sole tradespeople - extremely competitive entry point. Based in Oranmore, Co. Galway. | Pitch: Ciaran - Balnce automates the RCT and subcontractor management your tradespeople clients struggle with most. At their price point, every hour saved matters. | Sole focus on tradespeople. RCT, subcontractors. From €590. PERFECT fit.', updated_at = now() WHERE name = 'Accountants for Tradesmen';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'top', call_1_notes = 'agaisnt booking a call, wants more info on email. ', call_1_date = '2026-02-23', comments = 'Contact: Not found - check CRO #719694 | Intel: Website is heavily optimised/technical (NitroCD) suggesting they''re digitally savvy and open to new tech. | Pitch: Your tradesmen clients (builders, plumbers, electricians) can send you live expense data and RCT records through Balnce instead of shoeboxes of receipts. | Specialist accounting for Irish tradesmen. Builders, plumbers, electricians. Fixed-fee.', updated_at = now() WHERE name = 'FORTI Accountants';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'top', call_1_notes = 'have software and there not ready to disclose which one ( bs ) ', call_1_date = '2026-02-23', comments = 'Contact: John Byrne QFA PTP (Founder) | Intel: Explicitly lists hairdressers, barbers, carpenters, electricians, plumbers and says ''if your industry isn''t listed, contact us'' - casts a wide net across trades. | Pitch: John - your trades clients from carpenters to electricians could file expenses and track VAT in real-time through Balnce, cutting your admin at year-end. | Explicitly serves carpenters, plumbers, electricians, construction. Open Sat/Sun.', updated_at = now() WHERE name = 'Taxplus Accountants';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'top', call_1_notes = 'got email ', call_1_date = '2026-02-23', comments = 'Contact: William Twohig FCPA QFA (Principal). Team: Orla Hickey ACA, Lorraine Cuffe CPA, Graham O''Flynn CPA | Intel: 23+ years as SPECIALIST contractor accountants - their entire brand is built on contractor expertise. Team of 6 qualified staff. | Pitch: William - 23 years of contractor expertise means you know the pain of RCT paperwork. Balnce eliminates that friction for your contractor clients. | 23+ years contractor specialist. Fixed fees.', updated_at = now() WHERE name = 'Twohig & Co';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'top', call_1_notes = 'got email ', call_1_date = '2026-02-23', comments = 'Contact: Andrew Doherty (Founder & CEO) | Intel: Won Small Practice of the Year at Irish Accountancy Awards 2025! Recently relocated to new Athlone HQ. Finalist in 3 categories 2024. | Pitch: Andrew - congratulations on Small Practice of the Year! Balnce can help you scale that award-winning service to more SME clients without adding headcount. | Small Practice of the Year 2025. Irish SMEs.', updated_at = now() WHERE name = 'Incorpro Limited';
UPDATE public.crm_prospects SET stage = 'demo_booked', priority = 'top', call_1_notes = 'demo booked', call_1_date = '2026-02-23', demo_date = '2026-02-03', comments = 'Contact: Paschal O''Sullivan (Director) - trades as Paschal O''Sullivan & Co | Intel: Company incorporated 1998. Trades as both ACS Ltd and Paschal O''Sullivan & Co. | Pitch: Paschal - following up on your interest from November. Ready to get you set up with Balnce? Can do a quick 15-min demo this week. | Said yes after 24th Nov. OVERDUE - ring now.', updated_at = now() WHERE name = 'A.C.S. Ltd';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'high', call_1_notes = 'got email ', call_1_date = '2026-02-23', comments = 'Contact: Dermot Brennan (Managing Partner), Michael Byrne (Director) | Intel: Actively recruiting for Graduate Programme 2025-26 - growing firm. Trainee Lauren Cox praised their hands-on learning culture. | Pitch: Dermot - as you''re scaling the team, Balnce can reduce the manual data entry your grads spend hours on for construction sector clients. | Construction sector expertise. Serves Meath, Louth, Dublin.', updated_at = now() WHERE name = 'DBASS Chartered Accountants';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'high', call_1_notes = 'wrong number ', call_1_date = '2026-02-23', comments = 'Contact: Not found | Intel: Already using AI-powered forecasting and insights - very tech-forward for a Limerick practice. | Pitch: You''re already using AI-driven tools - Balnce integrates seamlessly and gives your construction clients automated RCT compliance and expense tracking. | Construction industry focus. Cloud accounting.', updated_at = now() WHERE name = 'AccountantLimerick.ie';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'high', call_1_notes = 'email ', call_1_date = '2026-02-23', comments = 'Contact: Tony Kirwan (Partner), Liam Somerville (Partner), Helena Burke (Tax Director) | Intel: 30+ years experience. ALL management staff are qualified accountants with registered tax advisers. IT, engineering AND construction contractors. | Pitch: Tony - your contractor clients across IT, engineering and construction all deal with similar compliance headaches. Balnce standardises that across sectors. | Contractors across IT, engineering, construction.', updated_at = now() WHERE name = 'GKS (Gannon Kirwan Somerville)';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'high', call_1_notes = 'email ', call_1_date = '2026-02-23', comments = 'Contact: Paul Redmond (Managing Partner), George Skelton (Tax), Kevin O''Donnell (Audit). Marie Kenny COO | Intel: Xero Digital Practice Champion 2024. 5 offices across SE Ireland. Core values: Respect, Trust, Honesty, Teamwork. | Pitch: Paul - as Xero champions you value tech that works. Balnce plugs straight into your cloud stack and gives your trade clients RCT + expense tracking. | Xero Digital Practice Champion 2024. 5 offices. Tech-forward.', updated_at = now() WHERE name = 'RDA Accountants';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'high', call_1_notes = 'email ', call_1_date = '2026-02-23', comments = 'Contact: Patrick Donnellan, Declan Murray, Gillian Carolan (Partners) | Intel: Dual certified as QuickBooks ProAdvisor AND Xero Advisor. Formed 2017 from merger of Kelly Murray + Donnellan Casserly. | Pitch: Patrick - you already champion Xero and QuickBooks. Balnce adds specialised RCT and trades compliance that those platforms don''t cover natively. | Founded 2017. Uses Xero & QuickBooks cloud. Startups focus.', updated_at = now() WHERE name = 'Candor Chartered Accountants';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'high', call_1_notes = 'email', call_1_date = '2026-02-22', comments = 'Contact: Gerard Kiernan FCCA (Founder & MD) | Intel: 17 years experience. Worked with thousands of contractors across IT, engineering, pharma, life sciences. Founded 2008. | Pitch: Gerard - after 17 years with thousands of contractors you know the admin pain. Balnce automates RCT and expense tracking for your trade clients.', updated_at = now() WHERE name = 'Icon Accounting';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'high', call_1_notes = 'email', call_1_date = '2026-02-23', comments = 'Contact: Raymond Gibbons (Founder & MD) | Intel: 95% client retention rate - they publicly promote this metric. Uses Sage Cloud. Tech-forward. | Pitch: Raymond - 95% retention shows your clients love you. Balnce adds automated RCT and expense tracking to your Sage Cloud stack for trade clients. | 95% retention. Sage Cloud. Tech-forward.', updated_at = now() WHERE name = 'BMS Accountants';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'high', call_1_notes = 'email', call_1_date = '2026-02-23', comments = 'Contact: Angela O''Leary (Founder/Managing Partner) | Intel: Philosophy: ''expertise delivered through simplicity.'' ''Know your business before crunching the first number.'' Software implementation specialists. | Pitch: Angela - you specialise in software implementation. Balnce is purpose-built for Irish trade clients'' RCT and expenses - perfect for your implementation expertise. | Software implementation & training. Tech-forward.', updated_at = now() WHERE name = 'AG Associates';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'uses sage, they give kick backs on auto cat ', call_1_date = '2026-02-23', comments = 'Contact: Diana Fitzgibbon (Principal) | Intel: Unique model: they go ON-SITE to clients rather than office-based. Competitive pricing by avoiding overhead. | Pitch: Diana - since you visit clients on-site, Balnce''s mobile app means your construction clients can capture receipts and expenses between your visits. | Construction, retail, hospitality clients since 2006.', updated_at = now() WHERE name = 'Kilkenny Accounting Services';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'email', call_1_date = '2026-02-23', comments = 'Contact: Owen McDonough FCA (Principal) | Intel: Family-run since 1969 (founded by Leo Hawkins). Owen joined 1976, brother Conor 1978. 50+ year legacy in West of Ireland. | Pitch: Owen - after 50+ years serving trades clients in the West, Balnce can modernise how your contractors handle RCT without changing your advisory relationship. | Trades, construction clients. 9 professionals. Since 1969.', updated_at = now() WHERE name = 'McDonough Hawkins & Co';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'pass my details on ', call_1_date = '2026-02-23', comments = 'Contact: Martin Quigley FCA (Partner), Ruairi Quigley FCA (Partner) | Intel: Also specialises in medical/dental sector - GPs, hospital consultants, dentists. Father-son partnership. | Pitch: Martin/Ruairi - your construction clients are juggling RCT, VAT and subcontractor payments. Balnce automates that so you can focus on advisory. | Construction, manufacturing, hotels. 30+ years.', updated_at = now() WHERE name = 'Martin Quigley & Co';
UPDATE public.crm_prospects SET stage = 'new_lead', priority = 'medium', call_1_date = '2026-02-23', comments = 'Contact: Barry Coffey (Partner), Donal Maher (Partner) - trades as Coffey Maher | Intel: Merger of Limerick Accounting Service (Barry) and Nenagh Accountancy Service (Donal). 35+ years combined across Limerick/Tipperary. | Pitch: Barry - your contractor and sole trader clients across Limerick and Tipperary could use Balnce to automate their RCT and expense tracking year-round. | 35+ years. Contractors, sole traders, publicans, retailers.', updated_at = now() WHERE name = 'Coffey & Co';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'voicemail ', call_1_date = '2026-02-23', comments = 'Contact: John Bond FACCA (Founder) - john@bondandco.ie | Intel: Fellow of ACCA. Swords location near Dublin Airport corridor - lots of trades/construction activity. | Pitch: John - circling back from December. Quick 15-min demo of how Balnce handles RCT compliance for your trade clients? | John Bond - call back in Dec. OVERDUE.', updated_at = now() WHERE name = 'Bond & Co';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'voice mail ', call_1_date = '2026-02-23', comments = 'Contact: Abid (first name only) | Intel: No web presence - may be a smaller sole practitioner practice in Drumcondra. | Pitch: Abid - following up from our December conversation. Still interested in seeing how Balnce can help your clients with tax compliance? | ABID - call 1pm 1st Dec. OVERDUE.', updated_at = now() WHERE name = 'A.A. Accounting';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'call back mid march ', call_1_date = '2026-02-23', comments = 'Contact: D.F. Byrne (initials only). Contact: Michael (employee) | Intel: Based in Barclay House, Pembroke Place, D2 - professional services hub area. | Pitch: Hi Michael - following up on our December conversation. Can I schedule a quick demo of Balnce for the partners? | Ring back Dec. Michael (employee). OVERDUE.', updated_at = now() WHERE name = 'Byrne D.F. & Associates';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'got email for dominic ', call_1_date = '2026-02-23', comments = 'Contact: Dominic Kenna (Director, 35+ years). Now trades as Kenna Accounting and Finance Solutions | Intel: 35+ years experience. Rebranded to Kenna Accounting and Finance Solutions. Blanchardstown Corporate Park. | Pitch: Dominic - following up on the email I sent to your manager. Would love to show you how Balnce saves time on trades client compliance. | Passing email to manager. Follow up - did manager get it?', updated_at = now() WHERE name = 'Kenna & Co';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'email', call_1_date = '2026-02-23', comments = 'Contact: Gail McEvoy CPA (Founder), Michael Craig FCA (Partner) | Intel: Recent Jan 2026 blog: ''What Expenses can I claim?'' Client testimonial praises ''consistent data for decision making.'' | Pitch: Gail - you just published an expenses guide for business owners. Balnce automates that exact process - real-time expense capture and categorisation. | Leading NE practice since 1999. 9 staff, 5 qualified.', updated_at = now() WHERE name = 'McEvoy Craig';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'emails ', call_1_date = '2026-02-23', comments = 'Contact: Kieran Lynch FCCA (Partner), Francis Lynch FCA (Partner). Founder Frank Lynch retired 2009. | Intel: Client testimonial: ''They are not just our auditors but an important part of our management team offering proactive advice.'' 50+ years. | Pitch: Kieran - your clients see you as part of their management team. Balnce gives you real-time financial data on trade clients to fuel that proactive advisory. | 50+ years. 2 offices.', updated_at = now() WHERE name = 'Frank Lynch & Co';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'email', call_1_date = '2026-02-23', comments = 'Contact: Bryan O''Donnell (Principal/Founder) | Intel: JUST MERGED with Somers Browne & Associates to expand services. Since 1997. Major growth moment. | Pitch: Bryan - congrats on the Somers Browne merger! As you expand services, Balnce can add automated RCT and expense tracking for your trade clients. | Since 1997. Outsourced accounting, payroll.', updated_at = now() WHERE name = 'O''Donnell + Co';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'email', call_1_date = '2026-02-23', comments = 'Contact: Anthony Ryan FCA (Founder), John Casey, Lisa Donohoe FCCA, Micheal Stafford FCCA/AITI, Robert Masterson ACA/CTA | Intel: Won ''Accountancy Firm of the Year'' at South-East Radio Customer Excellence Awards. 20 staff. | Pitch: Anthony - you won Firm of the Year for customer excellence. Balnce extends that excellence to your trade clients with automated RCT and expenses. | Award-winning. 20 staff. Free consultation.', updated_at = now() WHERE name = 'Anthony Ryan Accountants';
UPDATE public.crm_prospects SET stage = 'demo_booked', priority = 'medium', call_1_notes = 'demo booked, seemed really interested. Birthday on3/02 ', call_1_date = '2026-02-23', demo_date = '2026-03-03', comments = 'Contact: Ignatius McComb CIMA (Founder - 30+ years in manufacturing, construction, retail, food) | Intel: 30+ years across manufacturing, CONSTRUCTION, retail and food sectors. CIMA qualified. Est 2010. | Pitch: Ignatius - with your construction sector background you know the RCT pain firsthand. Balnce automates that for your trade clients. | Est 2010. Small firms & sole traders specialist.', updated_at = now() WHERE name = 'IMC Accountants';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'email', call_1_date = '2026-02-23', comments = 'Contact: Joe Cunnane FCA AITI CTA (Owner), Geraldine Beattie FCCA CTA (Tax Director). Darena = admin. | Intel: Publishes annual Budget analysis guides (Budget 2026 published Oct 2025). ''Proven tax recovery accountants.'' Contract worker specialists. | Pitch: Joe - you publish Budget guides and specialise in tax recovery. Balnce automates the day-to-day RCT and expense tracking for your contract worker clients. | Contract workers. Fixed pricing.', updated_at = now() WHERE name = 'TRA Professional Services';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'email ', call_1_date = '2026-02-23', comments = 'Contact: Muhammad S. Hafeez (Principal) | Intel: 30 years in outsourced accounting services. Long-established D15 practice. | Pitch: Muhammad - with 30 years in outsourced accounting, Balnce can automate the trades compliance work your team does manually. | No answer previously.', updated_at = now() WHERE name = 'MSH Accountants';
UPDATE public.crm_prospects SET stage = 'demo_booked', priority = 'medium', call_1_notes = 'hard to understand the accent ', call_1_date = '2026-02-23', demo_date = '2026-02-04', comments = 'Contact: Shijumon Chacko (Director/Founder) | Intel: Also runs TASC Outsourcing India - has international outsourcing capability. Est 2014 in Ireland. | Pitch: Shijumon - Balnce gives your Irish trade clients real-time expense tracking and RCT management that integrates with your outsourced workflows. | Voicemail previously.', updated_at = now() WHERE name = 'TASC Accountants';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'wrong number ', call_1_date = '2026-02-23', comments = 'Contact: Derek Christian (Director) + Murphy (second director since 2020) | Intel: Incorporated October 2016. Two-director firm in Swords - 68a Main Street. | Pitch: Derek - Balnce gives your sole trader and contractor clients real-time expense tracking and automated RCT compliance.', updated_at = now() WHERE name = 'Taxability';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'he hung up ', call_1_date = '2026-02-23', comments = 'Contact: Damien Malone FCCA (Founder & MD, Fellow Irish Tax Institute) | Intel: Founded by Jim Malone in 1950 - nearly 70 years! Jim served on Dundalk FC board 40 years and was FAI Vice President. | Pitch: Damien - with nearly 70 years of family heritage serving SMEs, Balnce can modernise how your trade clients handle RCT without losing the personal touch.', updated_at = now() WHERE name = 'Malone & Co';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'voicemail', call_1_date = '2026-02-23', comments = 'Contact: David Lafferty (Owner/Director) | Intel: Cloud-first practice: partners with cloud software to work with clients regardless of location or country. | Pitch: David - you already champion cloud accounting. Balnce adds specialised Irish RCT and trades compliance that generic platforms miss. | No answer previously.', updated_at = now() WHERE name = 'Accountable';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'no answer ', call_1_date = '2026-02-23', comments = 'Contact: Claire McNamara (Principal, Chartered Tax Adviser) | Intel: Expanding into estate and succession planning - helping clients hand over assets to children. Founded 1996. | Pitch: Claire - while you''re expanding into succession planning, Balnce can handle the day-to-day RCT and expense compliance for your sole trader clients. | Est 1996. Tax advisory specialists. Sole traders, partnerships, SMEs.', updated_at = now() WHERE name = 'Accounts Advice Centre';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'implementing new software, doesn’t know the name ', call_1_date = '2026-02-23', comments = 'Contact: Not found | Intel: Wix-based website. No team names disclosed. Camden Street D2 location. | Pitch: Do you serve any trade or construction clients? Balnce automates their RCT returns and expense tracking.', updated_at = now() WHERE name = 'Dublin Accountancy';
UPDATE public.crm_prospects SET stage = 'demo_booked', priority = 'medium', call_1_notes = 'likes idea of saving time, mostly sole traders and rental properties ', call_1_date = '2026-02-23', demo_date = '2026-03-03', comments = 'Contact: Gareth Murphy (Owner) | Intel: 25+ years experience. Sole traders and SMEs focus. Mobile number suggests accessible/personal service. | Pitch: Gareth - with 25 years advising sole traders you know the RCT paperwork burden. Balnce automates that for your trade clients. | 25+ years. Sole traders and SMEs.', updated_at = now() WHERE name = 'Dublin Tax Advisers';
UPDATE public.crm_prospects SET stage = 'demo_booked', priority = 'medium', call_1_notes = 'wants to see what its all about ', call_1_date = '2026-02-23', demo_date = '2026-03-10', comments = 'Contact: Richard Walsh (Founder - B.Comm NUIG + Diploma in Financial Trading) | Intel: Unusual combo: accounting degree + diploma in financial trading from DBS. Mobile number - personal service. | Pitch: Richard - your SME clients could capture expenses in real-time through Balnce instead of end-of-year scrambles.', updated_at = now() WHERE name = 'Everyday Accountancy';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'voicemail', call_1_date = '2026-02-23', comments = 'Contact: Karl McDonald (Principal - est 1976) | Intel: One of the longest-established practices on the list - since 1976. Nearly 50 years in Dublin 1. | Pitch: Karl - after nearly 50 years you''ve seen accounting go from ledgers to cloud. Balnce is the next step for your trade clients'' RCT and expenses.', updated_at = now() WHERE name = 'Karl McDonald & Co';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'voicemail', call_1_date = '2026-02-23', comments = 'Contact: Lorraine Whyte (Director - CRO 711757, incorporated 2022) | Intel: Relatively new incorporation (2022) - growing practice in Clontarf D3. | Pitch: Lorraine - as a growing practice, Balnce lets you serve more trade clients without proportionally increasing your admin workload.', updated_at = now() WHERE name = 'Lorraine Whyte Accountants';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'email ', call_1_date = '2026-02-23', comments = 'Contact: Martin Kelly (Owner - ICAI member) | Intel: ICAI (Chartered Accountants Ireland) member. North Strand Road, Dublin 3. | Pitch: Martin - Balnce gives your contractor clients automated RCT and expense tracking that saves you hours of manual data entry.', updated_at = now() WHERE name = 'Martin J. Kelly & Co';
UPDATE public.crm_prospects SET stage = 'demo_booked', priority = 'medium', call_1_notes = 'uses personal tax pro. Ros offline', call_1_date = '2026-02-23', demo_date = '2026-03-09', comments = 'Contact: Eamonn O''Connell (Principal) - eamonn@ocmc.ie | Intel: Company name OCMC MMX - the MMX is Roman numerals for 2010 (year of incorporation). | Pitch: Eamonn - Balnce automates the RCT and expense tracking for trade clients so you can focus on the advisory work that matters.', updated_at = now() WHERE name = 'OCMC Accountants';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'email', call_1_date = '2026-02-23', comments = 'Contact: Francis Brophy FCA (Principal, Authorised Personal Insolvency Practitioner). 30+ years. | Intel: FCA and also an Authorised Personal Insolvency Practitioner - dual expertise. 30+ years at Marino Mart, Fairview. | Pitch: Francis - your construction clients dealing with cash flow pressures need better real-time visibility. Balnce gives them automated expense and RCT tracking.', updated_at = now() WHERE name = 'Francis Brophy & Co';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'email', call_1_date = '2026-02-23', comments = 'Contact: Colum Whelan FCMA (Director - incorporated Feb 2024) | Intel: Very new company - incorporated February 2024. FCMA (Fellow of CIMA). | Pitch: Colum - as a brand new practice, Balnce lets you onboard trade clients faster with automated RCT and compliance from day one.', updated_at = now() WHERE name = 'Guardian Accounting';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'wrong number ', call_1_date = '2026-02-23', comments = 'Contact: Not found - CIMA registered practice | Intel: CIMA (management accounting) practice at Orchard House, Main Street, Rathfarnham. | Pitch: Do you serve any trade or construction clients? Balnce automates their RCT and expense management.', updated_at = now() WHERE name = 'Griffin & Associates';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'voicemail ', call_1_date = '2026-02-23', comments = 'Contact: Jaye McCarthy FCCA (Founder - statutory auditor + insolvency practitioner) | Intel: FCCA with dual specialisation: statutory auditor AND insolvency practitioner. Fitzwilliam Square. | Pitch: Jaye - your trade clients dealing with cash flow challenges need real-time expense visibility. Balnce gives them that plus automated RCT compliance.', updated_at = now() WHERE name = 'McCarthy Walsh';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'email', call_1_date = '2026-02-24', comments = 'Contact: Dermot Nutty FCCA, Patrick Minehane FCCA, Gary Copeland FCCA AITI (Directors). Founded 1983. | Intel: 3-director firm est 1983. Pride themselves on ''taking time to understand you and your business'' - tailored, not cookie-cutter. | Pitch: Dermot - you pride yourselves on understanding each client. Balnce gives you deeper real-time insight into your trade clients'' finances.', updated_at = now() WHERE name = 'McFeely & McKiernan';
UPDATE public.crm_prospects SET stage = 'demo_booked', priority = 'medium', call_1_notes = 'demo booked, real keen ', call_1_date = '2026-02-24', demo_date = '2026-03-09', comments = 'Contact: Sanjay (first name only - CRO 580901, est 2016) | Intel: Established 2016. Client testimonials reference Sanjay by first name - suggests very personal service style. | Pitch: Sanjay - Balnce automates RCT and expense tracking for trade clients, letting you maintain that personal advisory touch.', updated_at = now() WHERE name = 'SVCO Consultancy';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'voicemail', call_1_date = '2026-02-24', comments = 'Contact: Mohammad Mohsin Abbas FCA (Director) | Intel: FCA (Fellow of Chartered Accountants). Contact goes by ''Moh''. Naas Road D12. | Pitch: Moh - your SME clients in the trades could use Balnce to automate RCT and expenses instead of manual record-keeping.', updated_at = now() WHERE name = 'TAS Consulting';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'email', call_1_date = '2026-02-24', comments = 'Contact: Vincent Lynch (Principal - 45+ years family-run) | Intel: Family-run for 45+ years in Ballymount. Wix website suggests room for tech modernisation. | Pitch: Vincent - after 45 years of family tradition, Balnce can modernise how your trade clients handle RCT and expenses.', updated_at = now() WHERE name = 'VP Lynch & Co';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'email', call_1_date = '2026-02-24', comments = 'Contact: Sophie Dillon (Partner), Keith Murphy CPA (Partner), David Walsh AITI (Tax) | Intel: Three-partner firm in Dun Laoghaire. Sophie since 2001, Keith since 2014, David since 1998. | Pitch: Sophie/Keith - Balnce gives your sole trader and contractor clients real-time expense tracking and automated Irish tax compliance.', updated_at = now() WHERE name = 'Veldon Tait';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'against demo, uses sage big red cloud and others ', call_1_date = '2026-02-24', comments = 'Contact: John Mulderrig (Director since 2000 - firm est 1989) | Intel: 35+ years in Rathfarnham D14. Established web presence. | Pitch: John - Balnce automates RCT and expense tracking for trade clients, saving you hours of manual compliance work.', updated_at = now() WHERE name = 'John Mulderrig & Co';
UPDATE public.crm_prospects SET stage = 'demo_booked', priority = 'medium', call_1_notes = 'demo booked ', call_1_date = '2026-02-24', demo_date = '2026-03-09', comments = 'Contact: J.P. O''Donohoe (Principal) | Intel: Short memorable domain (jpod.ie). Newmarket D8 - near Coombe/Liberties area. | Pitch: J.P. - do your sole trader or contractor clients struggle with RCT and expenses? Balnce automates that entire workflow.', updated_at = now() WHERE name = 'JP O''Donohoe & Co';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'said no', call_1_date = '2026-02-24', comments = 'Contact: James Coyle (Chartered Accountant - Corporate Finance + Tax diplomas) | Intel: Chartered Accountant with specialised diplomas in Corporate Finance AND Taxation. Mobile number - accessible. | Pitch: James - with your tax diploma expertise, Balnce handles the routine RCT compliance for your trade clients so you focus on complex advisory.', updated_at = now() WHERE name = 'James Coyle & Co';
UPDATE public.crm_prospects SET stage = 'demo_booked', priority = 'medium', call_1_notes = 'Demo booked, hard sell ', call_1_date = '2026-02-24', demo_date = '2026-03-09', comments = 'Contact: Morgan Donnellan (MD), Austin Duke (Director). Also office in Tullow, Co. Carlow. | Intel: Two offices: Clanwilliam Square D2 and Tullow Co. Carlow. Serves both urban Dublin and rural SE clients. | Pitch: Morgan - with clients across Dublin and Carlow, Balnce gives your rural trade clients the same real-time compliance tools as your city ones.', updated_at = now() WHERE name = 'MJD Accountants';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'no answer ', comments = 'Contact: Richard Collins (Director since 2001) | Intel: Director since 2001 - 25+ years at the helm. Fitzwilliam Street D2. | Pitch: Richard - Balnce automates RCT and expense tracking for trade clients so your team spends less time on manual data entry.', updated_at = now() WHERE name = 'MAC Accountancy (MACS)';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'no answer ', comments = 'Contact: Richard Kidney (Owner), James Gleeson | Intel: Windsor Place D2 - prestigious Georgian Dublin address. Established practice. | Pitch: Richard - Balnce gives your contractor and sole trader clients automated RCT compliance and real-time expense tracking.', updated_at = now() WHERE name = 'Robert J. Kidney & Co';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'email', comments = 'Contact: Ian Dillon FCCA (Managing Partner), Ronan Lynch FCCA AITI (Partner) | Intel: Emphasis on ''deep understanding of client circumstances to create opportunities.'' Consultative, not transactional. | Pitch: Ian - you take a consultative approach. Balnce gives you deeper real-time financial data on your trade clients to fuel that advisory relationship.', updated_at = now() WHERE name = 'Dillon Kelly Cregan';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'no answer', comments = 'Contact: Brian Hogan (Principal) | Intel: Shankill area - South Dublin coast. Limited online presence. | Pitch: Brian - do you serve any trade or construction clients? Balnce automates their RCT and expense management.', updated_at = now() WHERE name = 'Brian Hogan & Co';
UPDATE public.crm_prospects SET stage = 'contacted', priority = 'medium', call_1_notes = 'no answer ', comments = 'Contact: Raymond (Ray) Hunt FCCA ITI (Principal) | Intel: FCCA AND Irish Tax Institute member - dual qualified. Rathmines D6. | Pitch: Ray - with your ITI membership you know Irish tax inside out. Balnce automates the routine RCT compliance so you focus on complex advisory.', updated_at = now() WHERE name = 'Hunt Raymond A. & Co';


-- Total updates: 59
